// Generated by CoffeeScript 1.10.0
(function() {
  describe('Calculator', function() {
    this.calc;
    beforeEach(function() {
      return this.calc = new Calculator();
    });
    describe('on add', function() {
      it('should add two positive numbers', function() {
        var a, b, expectedRes, res;
        a = 2;
        b = 3;
        expectedRes = 5;
        res = this.calc.add(a, b);
        return expect(res).toBe(expectedRes);
      });
      return it('should handle negative number addition', function() {
        var a, b, expectedRes, res;
        a = -10;
        b = 5;
        expectedRes = -5;
        res = this.calc.add(a, b);
        return expect(res).toBe(expectedRes);
      });
    });
    describe('on sub', function() {
      it('should subtract two positive numbers', function() {
        var a, b, expectedRes, res;
        a = 10;
        b = 6;
        expectedRes = 4;
        res = this.calc.sub(a, b);
        return expect(res).toBe(expectedRes);
      });
      return it('should handle negative number subtraction', function() {
        var a, b, expectedRes, res;
        a = 4;
        b = -6;
        expectedRes = 10;
        res = this.calc.sub(a, b);
        return expect(res).toBe(expectedRes);
      });
    });
    return describe('on mult', function() {
      it('should multiply positive numbers');
      return it('should multiply negative numbers');
    });
  });

}).call(this);

//# sourceMappingURL=calculator-tests.js.map
