// Generated by CoffeeScript 1.10.0
(function() {
  this.Calculator = (function() {
    function Calculator() {}

    Calculator.prototype.add = function(a, b) {
      return a + b;
    };

    Calculator.prototype.sub = function(a, b) {
      return a - b;
    };

    Calculator.prototype.mult = function(a, b) {
      return a * b;
    };

    Calculator.prototype.dev = function(a, b) {
      return a / b;
    };

    return Calculator;

  })();

}).call(this);

//# sourceMappingURL=calculator.js.map
