// Generated by CoffeeScript 1.10.0
(function() {
  var a, b, calc, res;

  calc = new Calculator();

  a = 1;

  b = 2;

  res = calc.add(a, b);

  console.log(a + " + " + b + " = " + res);

}).call(this);

//# sourceMappingURL=app.js.map
